version: 2.1
orbs:
  slack: narrativescience/slack@0.2.2
  windows: circleci/windows@2.4.0

 
jobs:
  build:
    docker:
      - image: <docker image>
    steps:
      - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: webhook

workflows:
  your-workflow:
    jobs:
      - build
