version: '2.1'
orbs:
  node: circleci/node@5.0.0
  slack: circleci/slack@4.4

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - notify_slack_error
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-secrets
    