version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1.28.0
  slack: circleci/slack@4.4.2

          
jobs:
  notify:
    executor:
      name: node/default
    steps:
      - slack/notify:
          channel: general
          event: fail
          template: basic_fail_1
          mentions: '@Jac'
      - slack/notify:
          channel: general
          event: pass
          template: success_tagged_deploy_1
          mentions: '@Jac'


workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run:
          record: true
          store_artifacts: true

      - notify:
          context: slack-secrets
  thirty-min-workflow:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run
      - notify:
          context: slack-secrets
