version: 2.1
orbs:
  slack: circleci/slack@4.4.4
  windows: circleci/windows@2.4.0
commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

  notify_slack_hold:
    steps:
      - slack/notify:
          event: fail
          template: basic_on_hold_1  
jobs:
  build:
    executor: windows/default
    steps:
      - run:
          command: "echo Hello, World!"
          shell: powershell.exe
      - notify_slack_error