version: 2.1

orbs:
  win: circleci/windows@2.2.0
  slack: signaldevs/slack@0.1.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            git clone https://github.com/course-hero/slacktee.git
            ls
            cd C:\Users\circleci\project\slacktee
            ls
            bash ./install.sh -s  C:\Users\bin
      - run:
          name: "Some name"
          command: |
            touch fromci.txt
            ./bin/script.sh ./fromci.txt
          shell: bash.exe