version: 2.1

orbs:
  win: circleci/windows@2.2.0
  slack: signaldevs/slack@0.1.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: bash.exe
          command: |
            git clone https://github.com/course-hero/slacktee.git
            bash ./slacktee/install.sh
      # Clone git repository


# Install slacktee.sh



      